### ISSUE TITLE
can't import 'vi-fetch/setup'

### ISSUE THREAD

**Issue by martinIvovIv** [sheremet-va/vi-fetch#12]
vi-fetch does not export setup, therefore it can't be imported.

**Comment by sheremet-va** [comment]
give reproduction, please

**Comment by martinIvovIv** [comment]
Hey @sheremet-va , sorry for the horrible issue I opened. 

It's an awesome package, I will add reproduction tomorrow, try to debug the problem (as it's most likely something stupid I'm doing) and otherwise I will contribute to the repo with the solution.

**Comment by martinIvovIv** [comment]
@sheremet-va 

I have a nextJS project (12.1.6) and I was trying to transition to Vitest from Jest.
I had my old 'setupTests' file and I had tried to import vi-fetch/setup there by mistake and forgotten about it.

Sorry about the lost time.
