### ISSUE TITLE
Expand typescript def to allow extending expect from jest

### ISSUE THREAD

**Issue by IanVS** [sheremet-va/vi-fetch#2]
Hi there, I'm moving over from web-test-runner to vitest, and instead of chai I'm using jest's [expect](https://www.npmjs.com/package/expect) assertion library.  I am finding that I can `declareFetchAssertions(expect);` and it seems to function correctly (although maybe I just haven't hit an edge case that causes problems), but unfortunately typescript complains because it's expecting (no pun intended) to get a `Chai.ExpectStatic`.  

So I guess I have a question and a request:

- Are there any issues with using vi-fetch matchers to extend expect?
- If not, could the typescript types be updated to accommodate for both uses?

**Comment by sheremet-va** [comment]
> Are there any issues with using vi-fetch matchers to extend expect?

It should be compatible with Vitest's expect as well as jest's expect

> If not, could the typescript types be updated to accommodate for both uses?

I will update the typescript types, sure

**Comment by sheremet-va** [comment]
Released under `0.4.2`
