### ISSUE TITLE
Testing Calls to Ky

### ISSUE THREAD

**Issue by cliedeman** [sheremet-va/vi-fetch#4]
Does this library support the Request style?

```js
fetch(new Request({...})
```

I am testing a library that  is using [ky](https://github.com/sindresorhus/ky)

**Comment by sheremet-va** [comment]
should work with it, but we don't provide Request/Response

**Comment by cliedeman** [comment]
I looked further into the docs and realized mws does what I need

https://vitest.dev/guide/mocking.html#requests
