### ISSUE TITLE
[Bug] Cannot set properties of undefined (setting 'Headers') in node environemt

### ISSUE THREAD

**Issue by thoughtspile** [sheremet-va/vi-fetch#6]
`import 'vi-fetch/setup'` throws in node vitest environment (`node@16`, no built-in fetch) since [setup](https://github.com/sheremet-va/vi-fetch/blob/main/src/setup.ts) sets `global.window.Headers` without checking if `window` exists

**Comment by sheremet-va** [comment]
Fixed in 0.7.1
