### ISSUE TITLE
Invalid Chai property: toHaveFetched

### ISSUE THREAD

**Issue by cmcculloh-kr** [sheremet-va/vi-fetch#8]
Using with sveltekit...

```javascript
import { mockFetch, mockGet } from 'vi-fetch';
import { brands } from '../brands';

describe('brands', () => {
	it('should init', async () => {
		const mock = mockGet('/default-brands').willResolve([{ sld: 'brand' }]);
		await brands.init();
		console.log('mock object:', mock);
		expect(mock).toHaveFetched();
	});
});
```

<img width="557" alt="image" src="https://user-images.githubusercontent.com/8006971/179290778-6483c5a7-c08c-4125-af83-cbc444fe96da.png">

**Comment by sheremet-va** [comment]
Did you set it up? https://github.com/sheremet-va/vi-fetch#setup

**Comment by cmcculloh-kr** [comment]
I thought I had, but it seems I was mistaken. I thought I could put `import 'vi-fetch/setup';` into `vitest.config.js` or `svelte.config.js`, but that doesn't work (noob mistake...).

For anyone else encountering this problem, here's what I had to do:

in `svelte.config.js`, in `config.kit.vite.test` add `setupFiles: 'vitest.setup.js'`, eg:
```javascript
const config = {
    kit: {
        vite: {
            test: {
                setupFiles: 'vitest.setup.js'
            }
        }
    }
}

export default config;
```

Then, create a file `vitest.setup.js`:
```javascript
import 'vi-fetch/setup';
```

Sorry about that! Thanks!
